"""
Notification Model
===================
Represents a system notification or alert generated by the alert evaluation
engine.  Alerts are role-targeted, entity-associated, and support resolution
lifecycle tracking.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import String, DateTime, ForeignKey, Text, Boolean, JSON, Index
from sqlalchemy.orm import Mapped, mapped_column

from app.database.database import Base


class Notification(Base):
    """
    Notifications table — stores operational and analytical alerts.

    Notes:
        - type:        camera_health | shelf_performance | product_visibility
                       | traffic_anomaly | platform
        - severity:    info | warning | critical
        - entity_type: camera | shelf | product | zone | ai_job | system
        - target_role: all | admin | store_manager | retail_analyst
                       | marketing_manager
        - is_read / is_resolved track notification lifecycle.
        - metadata stores arbitrary JSON context (scores, thresholds, etc.).
    """

    __tablename__ = "notifications"
    __table_args__ = (
        Index("ix_notifications_target_role_is_read", "target_role", "is_read"),
        Index("ix_notifications_store_id_type", "store_id", "type"),
        Index("ix_notifications_created_at_desc", "created_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )
    store_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("stores.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
        comment="FK to the parent store (nullable for system-wide alerts)",
    )
    type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="Alert category: camera_health, shelf_performance, product_visibility, traffic_anomaly, platform",
    )
    severity: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="info",
        comment="Alert severity: info, warning, critical",
    )
    title: Mapped[str] = mapped_column(
        String(300),
        nullable=False,
        comment="Short alert headline",
    )
    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Detailed alert description",
    )
    entity_type: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
        comment="Entity kind: camera, shelf, product, zone, ai_job, system",
    )
    entity_id: Mapped[uuid.UUID | None] = mapped_column(
        nullable=True,
        comment="UUID of the associated entity for deep-linking",
    )
    target_role: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="all",
        comment="Target audience role: all, admin, store_manager, retail_analyst, marketing_manager",
    )
    is_read: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        comment="Whether the notification has been read",
    )
    is_resolved: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        comment="Whether the underlying issue has been resolved",
    )
    metadata_json: Mapped[dict | None] = mapped_column(
        "metadata",
        JSON,
        nullable=True,
        comment="Arbitrary JSON context (scores, thresholds, metrics)",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when the alert was resolved",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    def __repr__(self) -> str:
        return f"<Notification(id={self.id}, type='{self.type}', severity='{self.severity}')>"
